### ISSUE TITLE
chore(net): Use Upstream Alloy Payload Types

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/op-rs#51]
### Description

The `net` crate currently defines custom execution payload types with SSZ support in the [payload](https://github.com/paradigmxyz/op-rs/blob/main/crates/net/src/types/payload.rs) module.

This ticket is to remove these types and re-use alloy types, moving any needed wrapper types into `op-alloy`.

**Comment by GrapeBaBa** [comment]
May I try to look it?

**Comment by merklefruit** [comment]
For sure!
