### ISSUE TITLE
chore(net): Remove NetworkAddress

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/op-rs#52]
### Description

Remove the intermediate [`NetworkAddress`](https://github.com/paradigmxyz/op-rs/blob/main/crates/net/src/types/address.rs#L10) type and instead use the standard library's [`SocketAddr`](https://doc.rust-lang.org/stable/std/net/enum.SocketAddr.html).

**Comment by vking45** [comment]
Hey, I would like to take up this issue, please assign it to me
